export default {
  player: {
    stage: 1,
    money: 100,
    ratio: 10,
    distance: 0,
    speed: 0,
  },
  upgrades: {
    fuel: {
      name: "fuel",
      speed: 1,
      cost: 1e2,
      lvl: 0,
      penatly: 0.1,
    },
    engine: {
      name: "engine",
      speed: 1e1,
      cost: 1e3,
      lvl: 0,
      penatly: 0.1,
    },
    booster: {
      name: "booster",
      speed: 1e2,
      cost: 1e4,
      lvl: 0,
      penatly: 0.1,
    },
    hull: {
      name: "hull",
      speed: 1e3,
      cost: 1e5,
      lvl: 0,
      penatly: 0.1,
    },
    fins: {
      name: "fins",
      speed: 1e4,
      cost: 1e6,
      lvl: 0,
      penatly: 0.1,
    },
    orbiter: {
      name: "orbiter",
      speed: 1e5,
      cost: 1e7,
      lvl: 0,
      penatly: 0.1,
    },
    tank: {
      name: "tank",
      speed: 1e6,
      cost: 1e8,
      lvl: 0,
      penatly: 0.1,
    },
    nose: {
      name: "nose",
      speed: 1e7,
      cost: 1e9,
      lvl: 0,
      penatly: 0.1,
    },
    wings: {
      name: "wings",
      speed: 1e8,
      cost: 1e10,
      lvl: 0,
      penatly: 0.1,
    },
  },
};
