export default {
  autosaveDelay: 30000,
  player: {
    stage: 1,
    money: 100,
    ratio: 10,
    distance: 0,
    speed: 0,
    afkRatio: 10,
    bonus: 1,
    tickSpeed: 1000,
  },
  upgrades: {
    fuel: {
      name: "fuel",
      speed: 1,
      cost: 1e2,
      lvl: 0,
      penatly: 0.1,
    },
    engine: {
      name: "engine",
      speed: 1e1,
      cost: 1e3,
      lvl: 0,
      penatly: 0.1,
    },
    booster: {
      name: "booster",
      speed: 1e2,
      cost: 1e4,
      lvl: 0,
      penatly: 0.1,
    },
    hull: {
      name: "hull",
      speed: 1e3,
      cost: 1e5,
      lvl: 0,
      penatly: 0.1,
    },
    fins: {
      name: "fins",
      speed: 1e4,
      cost: 1e6,
      lvl: 0,
      penatly: 0.1,
    },
    orbiter: {
      name: "orbiter",
      speed: 1e5,
      cost: 1e7,
      lvl: 0,
      penatly: 0.1,
    },
    tank: {
      name: "tank",
      speed: 1e6,
      cost: 1e8,
      lvl: 0,
      penatly: 0.1,
    },
    nose: {
      name: "nose",
      speed: 1e7,
      cost: 1e9,
      lvl: 0,
      penatly: 0.1,
    },
    wings: {
      name: "wings",
      speed: 1e8,
      cost: 1e10,
      lvl: 0,
      penatly: 0.1,
    },
    crew: {
      name: "crew",
      speed: 1e9,
      cost: 1e11,
      lvl: 0,
      penatly: 0.1,
    },
  },
  skins: {
    default_rocket: {
      name: "default_rocket",
      displayName: "Default",
      url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/default_rocket.png",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/default_rocket_icon.png",
      unlocked: true,
      selected: true,
      type: "rocket",
    },
    placeholder1: {
      name: "placeholder1",
      displayName: "placeholder",
      url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/rocket_placeholder.png",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/rocket_placeholder.png",
      unlocked: true,
      selected: false,
      type: "rocket",
    },
    placeholder2: {
      name: "placeholder2",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/rocket_placeholder.png",
      unlocked: false,
      selected: false,
      type: "rocket",
    },
    placeholder3: {
      name: "placeholder3",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/rocket_placeholder.png",
      unlocked: false,
      selected: false,
      type: "rocket",
    },
    placeholder4: {
      name: "placeholder4",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/rocket_placeholder.png",
      unlocked: false,
      selected: false,
      type: "rocket",
    },
    placeholder5: {
      name: "placeholder5",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/rocket_placeholder.png",
      unlocked: false,
      selected: false,
      type: "rocket",
    },
    placeholder6: {
      name: "placeholder6",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/rocket_placeholder.png",
      unlocked: false,
      selected: false,
      type: "rocket",
    },
    placeholder7: {
      name: "placeholder7",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/rocket_placeholder.png",
      unlocked: false,
      selected: false,
      type: "rocket",
    },
    placeholder8: {
      name: "placeholder8",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/rocket_placeholder.png",
      unlocked: false,
      selected: false,
      type: "rocket",
    },
    default_background: {
      name: "default_background",
      displayName: "Default",
      url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/galaxy.jpg",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/galaxy.jpg",
      unlocked: true,
      selected: true,
      type: "background",
    },
    generic_galaxy: {
      name: "generic_galaxy",
      displayName: "Generic",
      url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/background.jpg",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/background.jpg",
      unlocked: false,
      selected: false,
      type: "background",
    },
    placeholder10: {
      name: "placeholder10",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/background_placeholder.png",
      unlocked: false,
      selected: false,
      type: "background",
    },
    placeholder11: {
      name: "placeholder11",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/background_placeholder.png",
      unlocked: false,
      selected: false,
      type: "background",
    },
    placeholder12: {
      name: "placeholder12",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/background_placeholder.png",
      unlocked: false,
      selected: false,
      type: "background",
    },
    placeholder13: {
      name: "placeholder13",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/background_placeholder.png",
      unlocked: false,
      selected: false,
      type: "background",
    },
    placeholder14: {
      name: "placeholder14",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/background_placeholder.png",
      unlocked: false,
      selected: false,
      type: "background",
    },
    placeholder15: {
      name: "placeholder15",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/background_placeholder.png",
      unlocked: false,
      selected: false,
      type: "background",
    },
    placeholder16: {
      name: "placeholder16",
      displayName: "placeholder",
      url: "",
      icon_url: "https://raw.githubusercontent.com/logyQT/space-clicker/main/images/background_placeholder.png",
      unlocked: false,
      selected: false,
      type: "background",
    },
  },
};
